=== EsaieMuhasa/mlm-shivalik/PHPBackend/config.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT app-routes (module+)>
<!ELEMENT app-config (definitions?, users?)>
<!ELEMENT config (applications?, filters?, definitions?)>
<!ATTLIST config webData CDATA #REQUIRED> <!--Chemian vers le dossier pour stoker les donnee bruts-->
<!ATTLIST config webLogger CDATA #REQUIRED> <!-- Chemin vers le dossier log des erreurs -->


<!ELEMENT users (user+)>
<!ELEMENT definitions (define*, list*)>

<!--Pour les routes de l'application-->
<!--================================= -->
<!ELEMENT module (route+)>
<!ATTLIST module name ID #REQUIRED>

<!ELEMENT route EMPTY>
<!ATTLIST route urlPattern CDATA #REQUIRED>
<!ATTLIST route action CDATA #REQUIRED>
<!ATTLIST route paramsNames CDATA #IMPLIED>

<!-- histoire des filtres -->
<!-- ==================== -->
<!ELEMENT filters (filter+)>
<!ELEMENT filter (filter-route+)>
<!ATTLIST filter name CDATA #REQUIRED>

<!ELEMENT filter-route EMPTY>
<!ATTLIST filter-route urlPattern CDATA #REQUIRED>
<!ATTLIST filter-route prioriry CDATA #IMPLIED>
<!ATTLIST filter-route paramsNames CDATA #IMPLIED>


<!-- pour la balise manager -->
<!-- ====================== -->
<!ELEMENT dao (dbconnections+, entities?)>
<!ELEMENT dbconnections (connection+)>
<!ELEMENT connection EMPTY>
<!ATTLIST connection name ID #REQUIRED>
<!ATTLIST connection dsn CDATA #REQUIRED>
<!ATTLIST connection user CDATA #REQUIRED>
<!ATTLIST connection password CDATA #IMPLIED>
<!ATTLIST connection max CDATA #IMPLIED>

<!-- pour le entites -->
<!-- ====================== -->
<!ELEMENT entities (entity+)>
<!ELEMENT entity EMPTY>
<!ATTLIST entity name CDATA #REQUIRED><!-- Le nom simple de la classe qui incapsule l'entite -->
<!ATTLIST entity specification CDATA #REQUIRED>
<!ATTLIST entity implementation CDATA #REQUIRED>
<!ATTLIST entity alias CDATA #IMPLIED>

<!--pour une application -->
<!--==================== -->
<!ELEMENT applications (application+)>
<!ATTLIST applications foldName CDATA #REQUIRED>
<!ELEMENT application EMPTY>
<!ATTLIST application name ID #REQUIRED>
<!ATTLIST application urlPattern CDATA #IMPLIED><!-- pour l'application par defaut, le nom du sous domaine n'est pas obligatoire -->
<!ATTLIST application wsPort CDATA #IMPLIED><!-- le port ecouter par le WS -->
<!ATTLIST application wsListener CDATA #IMPLIED><!-- l'ecouteur du WS -->

<!-- -->
<!-- -->

<!--Les parametres de configuraion de l'application-->
<!ELEMENT define EMPTY>
<!ATTLIST define name ID #REQUIRED>
<!ATTLIST define value CDATA #REQUIRED>
<!ATTLIST define label CDATA #IMPLIED>


<!-- les attribut d'un utilisateur -->
<!ELEMENT user EMPTY>
<!ATTLIST user pseudo CDATA #REQUIRED>
<!ATTLIST user password CDATA #REQUIRED>

<!ELEMENT list (item+)>
<!ATTLIST list name ID #REQUIRED>
<!ATTLIST list label CDATA #IMPLIED><!-- utile lorsque l'item contien une liste -->
<!ELEMENT item (list?)><!-- pour une liste dans un element d'une liste -->
<!ATTLIST item name CDATA #REQUIRED>
<!ATTLIST item value CDATA #IMPLIED>
<!ATTLIST item label CDATA #IMPLIED>

=== EsaieMuhasa/mlm-shivalik/Config/dao.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dao SYSTEM "../PHPBackend/config.dtd" >
<dao>
	<dbconnections>
		<connection user="root" name="first" dsn="mysql:host=localhost;dbname=shivalik_db1"/>
		<!-- 
		<connection user="shivalik_db1" password="I45c9cKWv#" name="shivalik" dsn="mysql:host=localhost;dbname=shivalik_db1"/>
		 -->
	</dbconnections>
	
	<entities>
		<entity 
			name="\Core\Shivalik\Entities\BonusGeneration" 
			specification="\Core\Shivalik\Managers\BonusGenerationDAOManager"
			implementation="\Core\Shivalik\Managers\Implementation\BonusGenerationDAOManagerImplementation1"/>

		<entity 
			name="\Core\Shivalik\Entities\Country"
			specification="\Core\Shivalik\Managers\CountryDAOManager" 
			implementation="\Core\Shivalik\Managers\Implementation\CountryDAOManagerImplementation1"/>
			
		<entity 
			name="\Core\Shivalik\Entities\Generation"
			specification="\Core\Shivalik\Managers\GenerationDAOManager"
			implementation="\Core\Shivalik\Managers\Implementation\GenerationDAOManagerImplementation1"/>
		<entity 
			name="\Core\Shivalik\Entities\GradeMember" 
			specification="\Core\Shivalik\Managers\GradeMemberDAOManager" 
			implementation="\Core\Shivalik\Managers\Implementation\GradeMemberDAOManagerImplementation1"/>
			
		<entity 
			name="\Core\Shivalik\Entities\Grade" 
			specification="\Core\Shivalik\Managers\GradeDAOManager" 
			implementation="\Core\Shivalik\Managers\Implementation\GradeDAOManagerImplementation1"/>
			
		<entity 
			name="\Core\Shivalik\Entities\Localisation" 
			specification="\Core\Shivalik\Managers\LocalisationDAOManager" 
			implementation="\Core\Shivalik\Managers\Implementation\LocalisationDAOManagerImplementation1"/>
			
		<entity 
			name="\Core\Shivalik\Entities\Member"
			specification="\Core\Shivalik\Managers\MemberDAOManager"
			implementation="\Core\Shivalik\Managers\Implementation\MemberDAOManagerImplementation1"/>
			
		<entity
			name="\Core\Shivalik\Entities\VirtualMoney"
			specification="\Core\Shivalik\Managers\VirtualMoneyDAOManager"
			implementation="\Core\Shivalik\Managers\Implementation\VirtualMoneyDAOManagerImplementation1"/>
		
		<entity
			name="\Core\Shivalik\Entities\MoneyGradeMember"
			specification="\Core\Shivalik\Managers\MoneyGradeMemberDAOManager"
			implementation="\Core\Shivalik\Managers\Implementation\MoneyGradeMemberDAOManagerImplementation1"/>
				
		<entity 
			name="\Core\Shivalik\Entities\RequestVirtualMoney"
			specification="\Core\Shivalik\Managers\RequestVirtualMoneyDAOManager"
			implementation="\Core\Shivalik\Managers\Implementation\RequestVirtualMoneyDAOManagerImplementation1"/>
			
		<entity 
			name="\Core\Shivalik\Entities\Office"
			specification="\Core\Shivalik\Managers\OfficeDAOManager"
			implementation="\Core\Shivalik\Managers\Implementation\OfficeDAOManagerImplementation1"/>
			
		<entity 
			name="\Core\Shivalik\Entities\OfficeBonus" 
			specification="\Core\Shivalik\Managers\OfficeBonusDAOManager" 
			implementation="\Core\Shivalik\Managers\Implementation\OfficeBonusDAOManagerImplementation1"/>
			
		<entity 
			name="\Core\Shivalik\Entities\Size" 
			specification="\Core\Shivalik\Managers\SizeDAOManager" 
			implementation="\Core\Shivalik\Managers\Implementation\SizeDAOManagerImplementation1"/>
			
		<entity 
			name="\Core\Shivalik\Entities\OfficeSize" 
			specification="\Core\Shivalik\Managers\OfficeSizeDAOManager" 
			implementation="\Core\Shivalik\Managers\Implementation\OfficeSizeDAOManagerImplementation1"/>
			
		<entity 
			name="\Core\Shivalik\Entities\OfficeAdmin" 
			specification="\Core\Shivalik\Managers\OfficeAdminDAOManager" 
			implementation="\Core\Shivalik\Managers\Implementation\OfficeAdminDAOManagerImplementation1"/>
			
		<entity 
			name="\Core\Shivalik\Entities\PointValue" 
			specification="\Core\Shivalik\Managers\PointValueDAOManager" 
			implementation="\Core\Shivalik\Managers\Implementation\PointValueDAOManagerImplementation1"/>
		
		<entity 
			name="\Core\Shivalik\Entities\Category" 
			specification="\Core\Shivalik\Managers\CategoryDAOManager" 
			implementation="\Core\Shivalik\Managers\Implementation\CategoryDAOManagerImplementation1"/>
				
		<entity 
			name="\Core\Shivalik\Entities\Product" 
			specification="\Core\Shivalik\Managers\ProductDAOManager" 
			implementation="\Core\Shivalik\Managers\Implementation\ProductDAOManagerImplementation1"/>
			
		<entity 
			name="\Core\Shivalik\Entities\Stock" 
			specification="\Core\Shivalik\Managers\StockDAOManager" 
			implementation="\Core\Shivalik\Managers\Implementation\StockDAOManagerImplementation1"/>
			
		<entity 
			name="\Core\Shivalik\Entities\AuxiliaryStock" 
			specification="\Core\Shivalik\Managers\AuxiliaryStockDAOManager" 
			implementation="\Core\Shivalik\Managers\Implementation\AuxiliaryStockDAOManagerImplementation1"/>
		
		<entity 
			name="\Core\Shivalik\Entities\Command" 
			specification="\Core\Shivalik\Managers\CommandDAOManager" 
			implementation="\Core\Shivalik\Managers\Implementation\CommandDAOManagerImplementation1"/>
			
		<entity 
			name="\Core\Shivalik\Entities\ProductOrdered" 
			specification="\Core\Shivalik\Managers\ProductOrderedDAOManager" 
			implementation="\Core\Shivalik\Managers\Implementation\ProductOrderedDAOManagerImplementation1"/>
		
		<entity 
			name="\Core\Shivalik\Entities\MonthlyOrder" 
			specification="\Core\Shivalik\Managers\MonthlyOrderDAOManager" 
			implementation="\Core\Shivalik\Managers\Implementation\MonthlyOrderDAOManagerImplementation1"/>
				
		<entity 
			name="\Core\Shivalik\Entities\PurchaseBonus" 
			specification="\Core\Shivalik\Managers\PurchaseBonusDAOManager" 
			implementation="\Core\Shivalik\Managers\Implementation\PurchaseBonusDAOManagerImplementation1"/>
			
		<entity 
			name="\Core\Shivalik\Entities\Notification" 
			specification="\Core\Shivalik\Managers\NotificationDAOManager" 
			implementation="\Core\Shivalik\Managers\Implementation\NotificationDAOManagerImplementation1"/>
			
		<entity 
			name="\Core\Shivalik\Entities\NotificationReceiver" 
			specification="\Core\Shivalik\Managers\NotificationReceiverDAOManager" 
			implementation="\Core\Shivalik\Managers\Implementation\NotificationReceiverDAOManagerImplementation1"/>
			
		<entity 
			name="\Core\Shivalik\Entities\NotifiableComponent" 
			specification="\Core\Shivalik\Managers\NotifiableComponentDAOManager" 
			implementation="\Core\Shivalik\Managers\Implementation\NotifiableComponentDAOManagerImplementation1"/>
			
		<entity 
			name="\Core\Shivalik\Entities\Withdrawal" 
			specification="\Core\Shivalik\Managers\WithdrawalDAOManager" 
			implementation="\Core\Shivalik\Managers\Implementation\WithdrawalDAOManagerImplementation1"/>
			
		<entity 
			name="\Core\Shivalik\Entities\RaportWithdrawal" 
			specification="\Core\Shivalik\Managers\RaportWithdrawalDAOManager" 
			implementation="\Core\Shivalik\Managers\Implementation\RaportWithdrawalDAOManagerImplementation1"/>
			
		<entity 
			name="\Core\Shivalik\Entities\Transfer" 
			specification="\Core\Shivalik\Managers\TransferDAOManager" 
			implementation="\Core\Shivalik\Managers\Implementation\TransferDAOManagerImplementation1"/>
			
	</entities>
</dao>

=== EsaieMuhasa/mlm-shivalik/src/Applications/Member/Config/app-routes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE app-routes SYSTEM "../../../PHPBackend/config.dtd" >
<app-routes>

	<module name="Account">
	 	<route action="index" urlPattern="/member/"/>
	 	<route action="downlines" urlPattern="/member/downlines/"/>
	 	<route action="downlines" urlPattern="/member/downlines/(left|right|middle|all)\.html" paramsNames="foot"/>
	 	<route action="downlines" urlPattern="/member/downlines/(sponsorized)\.html" paramsNames="option"/>
	 	
	 	<route action="tree" urlPattern="/member/tree/"/>
	 	<route action="tree" urlPattern="/member/tree/(left|right|middle|all)\.(json|html)" paramsNames="foot,ext"/>
	 	<route action="tree" urlPattern="/member/tree/(left|right|middle|all)-(stack|tree)\.(json|html)" paramsNames="foot,affichage,ext"/>
	 	
	 	<route action="withdrawals" urlPattern="/member/withdrawals/"/>
	 	<route action="newWithdrawal" urlPattern="/member/withdrawals/new\.html"/>
	 	<route action="updateWithdrawal" urlPattern="/member/withdrawals/([0-9]+)/update\.html" paramsNames="id"/>
	 	<route action="history" urlPattern="/member/history/"/>
		<route action="history" urlPattern="/member/history/([0-9]{1,2})-([0-9]{4})\.html" paramsNames="month,year"/>
		<route action="history" urlPattern="/member/history/([0-9]{1,2})-([0-9]{1,2})-([0-9]{4})\.html" paramsNames="day,month,year"/>
	 	
	 	<route action="sellSheet" urlPattern="/member/sell-sheet/"/>
	 	<route action="sellSheet" urlPattern="/member/sell-sheet/([0-9]+)-([0-9]+)\.html" paramsNames="limit,offset"/>
	</module>
	
	<module name="Profil">
	 	<route action="index" urlPattern="/member/profil/"/>
	 	<route action="update" urlPattern="/member/profil/"/>
	 	
	 	<route action="password" urlPattern="/member/profil/password\.html"/>
	 	<route action="photo" urlPattern="/member/profil/photo\.html"/>
	 	<route action="address" urlPattern="/member/profil/address\.html"/>
	</module>
	
	<module name="MyOffice"><!-- monitoring de l'office -->
	 	<route action="index" urlPattern="/member/office/"/>
	 	<route action="withdrawals" urlPattern="/member/office/withdrawals/"/>
	 	<route action="withdrawals" urlPattern="/member/office/withdrawals/([0-9]+)-([0-9]+)\.html" paramsNames="limit,offset"/>
	 	<route action="members" urlPattern="/member/office/members/"/>
	 	<route action="upgrades" urlPattern="/member/office/upgrades\.html"/>
	 	<route action="members" urlPattern="/member/office/members/(table|grid)/" paramsNames="affichage"/>
	 	<route action="members" urlPattern="/member/office/members/(table|grid)/([0-9]+)-([0-9]+)\.html" paramsNames="affichage,limit,offset"/>
	 	<route action="virtualmoney" urlPattern="/member/office/virtualmoney/"/>
	 	<route action="sendRaportWithdrawals" urlPattern="/member/office/send-matched-money.html"/>
	 	<route action="requestVirtualmoney" urlPattern="/member/office/virtualmoney/request\.html"/>
	 	<route action="history" urlPattern="/member/office/history/"/>
		<route action="history" urlPattern="/member/office/history/([0-9]{1,2}-[0-9]{1,2}-[0-9]{4})\.html" paramsNames="date"/>
		<route action="history" urlPattern="/member/office/history/([0-9]{1,2})-([0-9]{4})\.html" paramsNames="month,year"/>
	 	<route action="index" urlPattern="/member/office/"/>
	</module>
	 	
</app-routes>

=== EsaieMuhasa/mlm-shivalik/Applications/Office/Config/app-routes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE app-routes SYSTEM "../../../PHPBackend/config.dtd" >

<app-routes>
	<module name="Dashboard">
	 	<route action="index" urlPattern="/office/"/>
	 	<route action="virtualMoney" urlPattern="/office/virtualmoney/"/>
	 	<route action="requestVirtualMoney" urlPattern="/office/virtualmoney/request\.html"/>
	</module>
	 
	<module name="Profil">
	 	<route action="index" urlPattern="/office/profil/"/>
	 	<route action="photo" urlPattern="/office/profil/photo\.html"/>
	 	<route action="password" urlPattern="/office/profil/password\.html"/>
	 	<route action="address" urlPattern="/office/profil/address\.html"/>
	</module>

	<module name="Members">
	 	<route action="index" urlPattern="/office/members/"/>
	 	<route action="index" urlPattern="/office/members/(table|grid)/" paramsNames="affichage"/>
	 	<route action="index" urlPattern="/office/members/([0-9]+)-([0-9]+)\.html" paramsNames="limit,offset"/>
	 	<route action="index" urlPattern="/office/members/(table|grid)/([0-9]+)-([0-9]+)\.html" paramsNames="affichage,limit,offset"/>
	 	<route action="addMember" urlPattern="/office/members/add\.html"/>
	 	
	 	<route action="member" urlPattern="/office/members/([0-9]+)/" paramsNames="id"/>
	 	<route action="upgradeMember" urlPattern="/office/members/([0-9]+)/(upgrade)\.html" paramsNames="id,option"/>
	 	<route action="downlines" urlPattern="/office/members/([0-9]+)/(downlines)/" paramsNames="id,option"/>
	 	<route action="downlines" urlPattern="/office/members/([0-9]+)/(downlines)/(left|middle|right|all)\.html" paramsNames="id,option,foot"/>
	
		<route action="withdrawalsMember" urlPattern="/office/members/([0-9]+)/(withdrawals)\.html" paramsNames="id,option"/>
		<route action="withdrawalsMember" urlPattern="/office/members/([0-9]+)/(withdrawals)/([0-9]+)\.html" paramsNames="id,option,requestId"/>
	</module>
	
	<module name="Products">
		<route action="index" urlPattern="/office/products/"/>
	</module>
</app-routes>

=== EsaieMuhasa/mlm-shivalik/src/Applications/Office/Config/app-routes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE app-routes SYSTEM "../../../PHPBackend/config.dtd" >

<app-routes>
	<module name="Dashboard">
	 	<route action="index" urlPattern="/office/"/>
	 	<route action="virtualMoney" urlPattern="/office/virtualmoney/"/>
	 	<route action="requestVirtualMoney" urlPattern="/office/virtualmoney/request\.html"/>
		<route action="virtualMoneyHistory" urlPattern="/office/virtualmoney/history\.html"/>
		<route action="virtualMoneyHistory" urlPattern="/office/virtualmoney/(\d{1,2}-\d{1,2}-\d{4})\.html" paramsNames="date"/>
		<route action="virtualMoneyHistory" urlPattern="/office/virtualmoney/(\d{1,2})-(\d{4})\.html" paramsNames="monthIndex,yearIndex"/>
	</module>
	 
	<module name="Profil">
	 	<route action="index" urlPattern="/office/profil/"/>
	 	<route action="photo" urlPattern="/office/profil/photo\.html"/>
	 	<route action="password" urlPattern="/office/profil/password\.html"/>
	 	<route action="address" urlPattern="/office/profil/address\.html"/>
	</module>

	<module name="Members">
	 	<route action="index" urlPattern="/office/members/"/>
	 	<route action="index" urlPattern="/office/members/(table|grid)/" paramsNames="affichage"/>
	 	<route action="index" urlPattern="/office/members/([0-9]+)-([0-9]+)\.html" paramsNames="limit,offset"/>
	 	<route action="index" urlPattern="/office/members/(table|grid)/([0-9]+)-([0-9]+)\.html" paramsNames="affichage,limit,offset"/>
	 	<route action="addMember" urlPattern="/office/members/add\.html"/>
	 	
	 	<route action="member" urlPattern="/office/members/([0-9]+)/" paramsNames="id"/>
	 	<route action="upgradeMember" urlPattern="/office/members/([0-9]+)/(upgrade)\.html" paramsNames="id,option"/>
	 	<route action="downlines" urlPattern="/office/members/([0-9]+)/(downlines)/" paramsNames="id,option"/>
	 	<route action="downlines" urlPattern="/office/members/([0-9]+)/(downlines)/(left|middle|right|all)\.html" paramsNames="id,option,foot"/>
	
	 	<route action="sellSheet" urlPattern="/office/members/([0-9]+)/(sell-sheet)/" paramsNames="id,option"/>
	 	<route action="addSellSheetRow" urlPattern="/office/members/([0-9]+)/(sell-sheet)/add\.html" paramsNames="id,option"/>
	 	<!-- afficliation d'un membre. pour un compte ayant des points valeur-->
		<route action="affiliateMember" urlPattern="/office/members/([0-9]+)/(affiliate)\.html" paramsNames="id,option"/>
	 	<!-- upgrade d'un compte membre. soit du proprietaire des point valeurs, soit d'un autre membre -->
		<route action="pvUpgradeMember" urlPattern="/office/members/([0-9]+)/pv-upgrade\.html" paramsNames="id"/>

		<route action="withdrawalsMember" urlPattern="/office/members/([0-9]+)/(withdrawals)\.html" paramsNames="id,option"/>
		<route action="withdrawalsMember" urlPattern="/office/members/([0-9]+)/(withdrawals)/([0-9]+)\.html" paramsNames="id,option,requestId"/>
	</module>
	
	<module name="Products">
		<!-- select commands of date -->
		<route action="index" urlPattern="/office/products/"/>
		<route action="index" urlPattern="/office/products/commands-of-([0-9]{1,2}-[0-9]{1,2}-[0-9]{4})/" paramsNames="date"/>
		<route action="index" urlPattern="/office/products/commands-of-([0-9]{1,2}-[0-9]{1,2}-[0-9]{4})/([0-9]+)-([0-9]+)\.html" paramsNames="date,limit,offset"/>
		<!-- // -->
		
		<!-- select commands of month -->
		<route action="index" urlPattern="/office/products/commands-of-([0-9]{1,2})-([0-9]{4})/" paramsNames="month,year"/>
		<route action="index" urlPattern="/office/products/commands-of-([0-9]{1,2})-([0-9]{4})/([0-9]+)-([0-9]+)\.html" paramsNames="month,year,limit,offset"/>
		<!-- // -->
		
		<!-- select commands of week -->
		<route action="index" urlPattern="/office/products/commands-of-([0-9]{1,2}-[0-9]{1,2}-[0-9]{4})-to-([0-9]{1,2}-[0-9]{1,2}-[0-9]{4})-week-([0-5])/" paramsNames="firstDay,lastDay,week"/>
		<route action="index" urlPattern="/office/products/commands-of-([0-9]{1,2}-[0-9]{1,2}-[0-9]{4})-to-([0-9]{1,2}-[0-9]{1,2}-[0-9]{4})-week-([0-5])/([0-9]+)-([0-9]+)\.html" paramsNames="firstDay,lastDay,week,limit,offset"/>
		<!-- // -->
		
		<route action="products" urlPattern="/office/products/vailable/"/>
		
		<route action="command" urlPattern="/office/products/command/"/>
		<route action="command" urlPattern="/office/products/command/pdf\.pdf"/>
		<route action="command" urlPattern="/office/products/commands/([0-9]+)/(pdf)\.pdf" paramsNames="id,option"/>
		<route action="command" urlPattern="/office/products/commands/([0-9]+)/(delivered)\.html" paramsNames="id,option"/>
		
		<route action="validateCommand" urlPattern="/office/products/command/validate\.html"/>
		<route action="cancelCommand" urlPattern="/office/products/command/cancel\.html"/>
		<route action="memberCommand" urlPattern="/office/products/command/member\.html"/>
		<route action="productCommand" urlPattern="/office/products/command/product\.html"/>
		
		<!-- to manage member file content monthly bonus -->
		<route action="purchase" urlPattern="/office/products/purchase/"/>
		<route action="purchase" urlPattern="/office/products/purchase/([0-9]+)-([0-9]+)\.html" paramsNames="limit,offset"/>
		<route action="addPurchase" urlPattern="/office/products/purchase/add\.html"/>
		<!-- // -->
	</module>
</app-routes>

=== EsaieMuhasa/mlm-shivalik/Applications/Common/Config/app-routes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE app-routes SYSTEM "../../../PHPBackend/config.dtd" >
<app-routes>
	
	<module name="Index">
	 	<route action="index" urlPattern="/"/>
	 	<route action="index" urlPattern="/index.html"/>
	 	<route action="about" urlPattern="/about.html"/>
	 	<route action="contact" urlPattern="/contact.html"/>
	</module>
	
	<module name="News">
		<route action="index" urlPattern="/news/"/>
		<route action="index" urlPattern="/news/index.html"/>
	</module>
	
	<module name="Authentification">
	 	<route action="login" urlPattern="/login\.html"/>
	 	<route action="logout" urlPattern="/logout\.html"/>
	</module>
	
</app-routes>
